"""
Set of "markup" template filters for Django.  These filters transform plain text
markup syntaxes to HTML; currently there is support for:
    * Textile, which requires the PyTextile library available at
      http://loopcore.com/python-textile/
    * Markdown, which requires the Python-markdown library from
      http://www.freewisdom.org/projects/python-markdown
    * reStructuredText, which requires docutils from http://docutils.sf.net/
"""

import warnings

from django import template
from django.conf import settings
from django.utils.encoding import smart_bytes, force_text
from django.utils.safestring import mark_safe


def markdown(value, arg=''):
    """
    Runs Markdown over a given value, optionally using various
    extensions python-markdown supports.
    Syntax::
        {{ value|markdown:"extension1_name,extension2_name..." }}
    To enable safe mode, which strips raw HTML and only returns HTML
    generated by actual Markdown syntax, pass "safe" as the first
    extension in the list.
    If the version of Markdown in use does not support extensions,
    they will be silently ignored.
    """
    try:
        import markdown as md
    except ImportError:
        raise template.TemplateSyntaxError("Error in 'markdown' filter: The Python markdown library isn't installed.")
    else:
        # markdown.version was first added in 1.6b. The only version of markdown
        # to fully support extensions before 1.6b was the shortlived 1.6a.
        if hasattr(md, 'version'):
            extensions = [e for e in arg.split(",") if e]
            if len(extensions) > 0 and extensions[0] == "safe":
                extensions = extensions[1:]
                safe_mode = True
            else:
                safe_mode = False
            python_markdown_deprecation = ("The use of Python-Markdown "
            "< 2.1 in Django is deprecated; please update to the current version")
            # Unicode support only in markdown v1.7 or above. Version_info
            # exist only in markdown v1.6.2rc-2 or above.
            markdown_vers = getattr(md, "version_info", None)
            if markdown_vers < (1,7):
                warnings.warn(python_markdown_deprecation, DeprecationWarning)
                return mark_safe(force_text(markdown.markdown(smart_bytes(value), safe_mode=safe_mode)))
            else:
                if markdown_vers >= (2,1):
                    if safe_mode:
                        return mark_safe(md.markdown(force_text(value), safe_mode=safe_mode))
                    else:
                        return mark_safe(md.markdown(force_text(value), safe_mode=safe_mode))
                else:
                    warnings.warn(python_markdown_deprecation, DeprecationWarning)
                    return mark_safe(md.markdown(force_text(value), safe_mode=safe_mode))
        else:
            python_markdown_deprecation = ("The use of Python-Markdown "
                "< 2.1 in Django is deprecated; please update to the current version")
            warnings.warn(python_markdown_deprecation, DeprecationWarning)
            return mark_safe(force_text(md.markdown(smart_bytes(value))))
