# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-25 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('string', models.CharField(db_index=True, max_length=35)),
                ('blob', models.TextField()),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('defer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deferee', to='wikisyntax.Blob')),
            ],
        ),
    ]
