# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-25 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikisyntax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blob',
            name='string',
            field=models.CharField(blank=True, db_index=True, max_length=35, null=True, unique=True),
        ),
    ]
