# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-25 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikisyntax', '0002_auto_20170325_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blob',
            name='updated',
        ),
        migrations.AddField(
            model_name='blob',
            name='accessed',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 3, 25, 5, 0, 43, 664148)),
            preserve_default=False,
        ),
    ]
